.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel bkGetSR
    /* F36810 8025AFE0 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* F36814 8025AFE4 03E00008 */  jr         $ra
    /* F36818 8025AFE8 00000000 */   nop
endlabel bkGetSR
    /* F3681C 8025AFEC 00000000 */  nop
