.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel bkmemcpy64
    /* F2E840 80253010 000630C2 */  srl        $a2, $a2, 3
  .L80253014:
    /* F2E844 80253014 DCA80000 */  ld         $t0, 0x0($a1)
    /* F2E848 80253018 20C6FFFF */  addi       $a2, $a2, -0x1 /* handwritten instruction */
    /* F2E84C 8025301C 20840008 */  addi       $a0, $a0, 0x8 /* handwritten instruction */
    /* F2E850 80253020 20A50008 */  addi       $a1, $a1, 0x8 /* handwritten instruction */
    /* F2E854 80253024 14C0FFFB */  bnez       $a2, .L80253014
    /* F2E858 80253028 FC88FFF8 */   sd        $t0, -0x8($a0)
    /* F2E85C 8025302C 03E00008 */  jr         $ra
    /* F2E860 80253030 00000000 */   nop
endlabel bkmemcpy64

/* Handwritten function */
glabel bkmemset64
    /* F2E864 80253034 000630C2 */  srl        $a2, $a2, 3
  .L80253038:
    /* F2E868 80253038 20C6FFFF */  addi       $a2, $a2, -0x1 /* handwritten instruction */
    /* F2E86C 8025303C FC850000 */  sd         $a1, 0x0($a0)
    /* F2E870 80253040 14C0FFFD */  bnez       $a2, .L80253038
    /* F2E874 80253044 20840008 */   addi      $a0, $a0, 0x8 /* handwritten instruction */
    /* F2E878 80253048 03E00008 */  jr         $ra
    /* F2E87C 8025304C 00000000 */   nop
endlabel bkmemset64
